#!/bin/bash

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.

# Run all tests

###
### "includes"
###

source fixture/config
source fixture/setup
source fixture/teardown

###
### "main"
###

setup

numPassed=0
numFailed=0

for t in $(ls -1 *.test)
do
    ./$t
    r=$?
    if [[ $r == 0 ]] ; then
        let numPassed=$numPassed+1
    else
        let numFailed=$numFailed+$r
    fi
done

echo
echo "=========================================================="
echo "Tests passed: $numPassed"
echo "Tests failed: $numFailed"
echo "=========================================================="

teardown
