#!/bin/bash

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  

# usage: assert testname testresult msg debug-info

testname=$1
testresult=$2
msg=$3
info=$4

if [[ $2 == 0 ]]; then
    echo "$(tput setaf 2)${testname}: passed$(tput sgr0)"
else
    echo "$(tput setaf 1)${testname}: failed"
    echo -e "    ${msg}$(tput sgr0)"
    if [[ $info ]] ; then
        echo "$(tput setaf 1)    ${info}$(tput sgr0)"        
    fi
    exit 1
fi
